build tool for php54 scl

diff --git a/tools/buildfct b/tools/buildfct
--- a/tools/buildfct
+++ b/tools/buildfct
@@ -70,6 +70,7 @@ alias mockfc19i="  setarch i686  mock --configdir=$mocketc -r fc19i   --arch i68
 alias mockfc19i56="setarch i686  mock --configdir=$mocketc -r fc19i56 --arch i686 rebuild "
 alias mockfc19x="                mock --configdir=$mocketc -r fc19x               rebuild "
 alias mockfc19x56="              mock --configdir=$mocketc -r fc19x56             rebuild "
+alias mockfc19xscl54="           mock --configdir=$mocketc -r fc19xscl54          rebuild "
 alias mockfc19xscl56="           mock --configdir=$mocketc -r fc19xscl56          rebuild "
 alias mockfc19xd="               mock --configdir=$mocketc -r fc19xd              rebuild "
 
@@ -77,11 +78,13 @@ alias mockfc20i="  setarch i686  mock --configdir=$mocketc -r fc20i   --arch i68
 alias mockfc20i56="setarch i686  mock --configdir=$mocketc -r fc20i56 --arch i686 rebuild "
 alias mockfc20x="                mock --configdir=$mocketc -r fc20x               rebuild "
 alias mockfc20x56="              mock --configdir=$mocketc -r fc20x56             rebuild "
+alias mockfc20xscl54="           mock --configdir=$mocketc -r fc20xscl54          rebuild "
 alias mockfc20xscl56="           mock --configdir=$mocketc -r fc20xscl56          rebuild "
 alias mockfc20xd="               mock --configdir=$mocketc -r fc20xd              rebuild "
 
 alias mockfc21i="  setarch i686  mock --configdir=$mocketc -r fc21i   --arch i686 rebuild "
 alias mockfc21x="                mock --configdir=$mocketc -r fc21x               rebuild "
+alias mockfc21xscl54="           mock --configdir=$mocketc -r fc21xscl54          rebuild "
 
 #alias mockel4i="setarch i686  mock --configdir=$mocketc -r el4i  --arch i386 rebuild "
 #alias mockel4it="setarch i686 mock --configdir=$mocketc -r el4it --arch i386 rebuild "
@@ -105,15 +108,15 @@ alias mockel6x="               mock --configdir=$mocketc -r el6x               r
 alias mockel6xt="              mock --configdir=$mocketc -r el6xt              rebuild "
 alias mockel6x55="             mock --configdir=$mocketc -r el6x55             rebuild "
 alias mockel6x56="             mock --configdir=$mocketc -r el6x56             rebuild "
+alias mockel6xscl54="          mock --configdir=$mocketc -r el6xscl54          rebuild "
 alias mockel6xscl56="          mock --configdir=$mocketc -r el6xscl56          rebuild "
 
 alias mockel7x="               mock --configdir=$mocketc -r el7x               rebuild "
 alias mockel7xt="              mock --configdir=$mocketc -r el7xt              rebuild "
 alias mockel7x55="             mock --configdir=$mocketc -r el7x55             rebuild "
 alias mockel7x56="             mock --configdir=$mocketc -r el7x56             rebuild "
+alias mockel7xscl54="          mock --configdir=$mocketc -r el7xscl54          rebuild "
 alias mockel7xscl56="          mock --configdir=$mocketc -r el7xscl56          rebuild "
-
-alias mockscl="                mock --configdir=$mocketc -r el6xscl54          rebuild "
 
 alias mockdevi="setarch i686 mock -r fedora-devel-i386   rebuild "
 alias mockdevx="             mock -r fedora-devel-x86_64 rebuild "
@@ -336,7 +339,7 @@ if [ "$1" = "-q" ]; then
 fi
 
 if [ -f "$1" ]; then
-  for i in $(seq 20 -1 19)
+  for i in $(seq 19 1 20)
   do
     echo -n "$(date +%X) scl56 fc$i "
     mock $quiet --configdir=$mocketc -r fc${i}xscl56 rebuild $1 && echo " Ok." || echo " Error !"
@@ -345,6 +348,32 @@ if [ -f "$1" ]; then
   do
     echo -n "$(date +%X) scl56 el$i  "
     mock $quiet --configdir=$mocketc -r el${i}xscl56 rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  date +%X
+else
+  echo "file not found '$1'"
+fi
+}
+
+# Build All distribution / version / 64bits for remi/scl-php54
+mockscl54x()
+{
+quiet=""
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  for i in $(seq 19 1 21)
+  do
+    echo -n "$(date +%X) scl54 fc$i "
+    mock $quiet --configdir=$mocketc -r fc${i}xscl54 rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  for i in $(seq 7 -1 6)
+  do
+    echo -n "$(date +%X) scl54 el$i  "
+    mock $quiet --configdir=$mocketc -r el${i}xscl54 rebuild $1 && echo " Ok." || echo " Error !"
   done
   date +%X
 else
