add helper for php56 noach packages

diff --git a/tools/buildfct b/tools/buildfct
--- a/tools/buildfct
+++ b/tools/buildfct
@@ -407,6 +407,43 @@ else
 fi
 }
 
+# Build All distribution / version / noarch for remi/remi-php56
+mock56t()
+{
+quiet="--quiet"
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  date +%X
+  pids=""
+  for i in 21 22 23
+  do
+    echo -n ""
+    (mock $quiet --configdir=$mocketc -r fc${i}xt  rebuild $1 && echo "$(date +%X) (56) fc$i  Ok." || echo "fc$1 Error !")&
+    pids="$pids $!"
+  done
+  for i in 20 19
+  do
+    echo -n ""
+    (mock $quiet --configdir=$mocketc -r fc${i}t56 rebuild $1 && echo "$(date +%X) (56) fc$i  Ok." || echo "fc$1 Error !")&
+    pids="$pids $!"
+  done
+  for i in 7 6 5
+  do
+    echo -n ""
+    (mock $quiet --configdir=$mocketc -r el${i}t56 rebuild $1 && echo "$(date +%X) (56) el$i   Ok." || echo "el$i  Error !")&
+    pids="$pids $!"
+  done
+  wait $pids
+  date +%X
+else
+  echo "file not found '$1'"
+fi
+}
+
 # Build All distribution / version / 64bits for remi/remi-php55
 mock55x()
 {
