add help for noarch with php > 5.5

diff --git a/tools/buildfct b/tools/buildfct
--- a/tools/buildfct
+++ b/tools/buildfct
@@ -331,6 +331,37 @@ else
 fi
 }
 
+# Build All distribution / version / noarch for remi/remi-php55
+mock55n()
+{
+quiet="--quiet"
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  date +%X
+  pids=""
+  for i in 21 22 20 19
+  do
+    echo -n ""
+    (mock $quiet --configdir=$mocketc -r fc${i}x   rebuild $1 && echo "$(date +%X) (55+) fc$i  Ok." || echo "fc$1 Error !")&
+    pids="$pids $!"
+  done
+  for i in 7 6 5
+  do
+    echo -n ""
+    (mock $quiet --configdir=$mocketc -r el${i}x55 rebuild $1 && echo "$(date +%X) (55)  el$i   Ok." || echo "el$i  Error !")&
+    pids="$pids $!"
+  done
+  wait $pids
+  date +%X
+else
+  echo "file not found '$1'"
+fi
+}
+
 # Build All distribution / version / 64bits for remi/remi-php55
 mock55x()
 {
