prepare move of php55 to remi for fedora

diff --git a/tools/buildfct b/tools/buildfct
--- a/tools/buildfct
+++ b/tools/buildfct
@@ -94,6 +94,7 @@ alias mockel6x55="             mock --configdir=$mocketc -r el6x55             r
 alias mockdevi="setarch i686 mock -r fedora-devel-i386   rebuild "
 alias mockdevx="             mock -r fedora-devel-x86_64 rebuild "
 
+# Build All distribution / version / 32bits for remi
 mockalli()
 {
 quiet=""
@@ -118,6 +119,53 @@ else
 fi
 }
 
+# Temporary / 32bits for remi
+mockoldi()
+{
+quiet=""
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  for i in $(seq 16 -1 14)
+  do
+    echo -n "$(date +%X) fc$i "
+    setarch i686  mock $quiet --configdir=$mocketc -r fc${i}i --arch i686 rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  date +%X
+else
+  echo "file not found p$1'"
+fi
+}
+
+# Build All distribution / version / 32bits for remi/remi-php55
+mock55i()
+{
+quiet=""
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  for i in $(seq 20 -1 14)
+  do
+    echo -n "$(date +%X) fc$i "
+    setarch i686  mock $quiet --configdir=$mocketc -r fc${i}i --arch i686 rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  echo -n "$(date +%X) el6  "
+  setarch i686    mock $quiet --configdir=$mocketc -r el6i55  --arch i686 rebuild $1 && echo " Ok." || echo " Error !"
+  echo -n "$(date +%X) el5  "
+  setarch i686    mock $quiet --configdir=$mocketc -r el5i55  --arch i386 rebuild $1 && echo " Ok." || echo " Error !"
+  date +%X
+else
+  echo "file not found p$1'"
+fi
+}
+
+# Build all distribution / version / 32bits for remi-test
 mockallit()
 {
 quiet=""
@@ -127,7 +175,7 @@ if [ "$1" = "-q" ]; then
 fi
 
 if [ -f "$1" ]; then
-  for i in $(seq 18 -1 17)
+  for i in $(seq 20 -1 18)
   do
     echo -n $(date +%X) test-fc$i
     setarch i686  mock $quiet --configdir=$mocketc -r fc${i}it  --arch i686 rebuild $1 && echo " Ok." || echo " Error !"
@@ -142,6 +190,7 @@ else
 fi
 }
 
+# Build All distribution / version / 64bits for remi
 mockallx()
 {
 quiet=""
@@ -167,6 +216,54 @@ else
 fi
 }
 
+# Temporary / 64bits for remi
+mockallx()
+{
+quiet=""
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  for i in $(seq 16 -1 14)
+  do
+    echo -n $(date +%X) fc$i
+    mock $quiet --configdir=$mocketc -r fc${i}x rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  date +%X
+else
+  echo "file not found '$1'"
+fi
+}
+
+# Build All distribution / version / 64bits for remi/remi-php55
+mock55x()
+{
+quiet=""
+if [ "$1" = "-q" ]; then
+    quiet="--quiet"
+    shift
+fi
+
+if [ -f "$1" ]; then
+  for i in $(seq 20 -1 14)
+  do
+    echo -n "$(date +%X) fc$i "
+    mock $quiet --configdir=$mocketc -r fc${i}x rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  for i in $(seq 6 -1 5)
+  do
+    echo -n "$(date +%X) el$i  "
+    mock $quiet --configdir=$mocketc -r el${i}x55 rebuild $1 && echo " Ok." || echo " Error !"
+  done
+  date +%X
+else
+  echo "file not found '$1'"
+fi
+}
+
+# Build All distribution / version / 64bits for remi-test
 mockallxt()
 {
 quiet=""
@@ -176,7 +273,7 @@ if [ "$1" = "-q" ]; then
 fi
 
 if [ -f "$1" ]; then
-  for i in $(seq 18 -1 17)
+  for i in $(seq 20 -1 18)
   do
     echo -n $(date +%X) test-fc$i
     mock $quiet --configdir=$mocketc -r fc${i}xt rebuild $1 && echo " Ok." || echo " Error !"
